name: Calculate ELO

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
    inputs:
      force-run:
        description: "Force run"
        required: false
        default: false
        type: boolean

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.head_ref || github.run_id }}-${{ github.workflow }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install supabase scikit-learn pandas numpy

      - name: Run calculations
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python src/calculate_elo.py
